x = float(input("Insira um valor: "))
y = float(input("Insira outro valor: "))
z = float(input("Insira outro valor: "))
s = ((x**2)+(y**2)+(z**2))
print ("A soma do quadrados dos números {}, {} e {} é {:.3f}".format(x, y, z, s))